export const ALL_CUSTOMER_MENU_SUCCESS = "ALL_CUSTOMER_MENU_SUCCESS"
export const ALL_CUSTOMER_MENU_FAIL = "ALL_CUSTOMER_MENU_FAIL"
export const CLEAR_ERRORS = "CLEAR_ERRORS"
export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART"
export const REMOVE_ITEM = 'REMOVE_ITEM'
export const CLEAR_ITEM_FROM_CART = 'CLEAR_ITEM_FROM_CART'