import React, { useEffect, useState } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import Head from 'next/head';
import axios from 'axios';
import Button from '@mui/material/Button';
import Grid from '@mui/material/Grid';
import TextField from '@mui/material/TextField';
import DialogActions from '@mui/material/DialogActions';
import DialogContent from '@mui/material/DialogContent';
import DialogTitle from '@mui/material/DialogTitle';
import { useRouter } from 'next/router';
import { BASE_URL_HOST } from '../../config/config';
import { LoadingButton } from '@mui/lab';

export default function changePassword() {
  const router = useRouter();
  const { token } = router.query;
  const [payload, setPayload] = useState({
    newPassword: '',
  });
  const [isChanged, setIsChanged] = useState(false);
  const [errorMsg, setErrorMsg] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  useEffect(() => {
    // setIsChanged(false);
    setIsLoading(false);
  }, []);

  const handleChange = (name, value) => {
    setPayload({
      newPassword: value,
    });
  };
  const handleSubmit = e => {
    e.preventDefault();
    setIsLoading(true);
    axios({
      url: `${BASE_URL_HOST}/auth/change-password`,
      method: 'patch',
      data: {
        password: payload.newPassword,
        token: token,
      },
    })
      .then(response => {
        if (response.status === 200) {
          setIsChanged(true);
          setIsLoading(false);
        }
        console.log();
      })
      .catch(err => {
        setIsLoading(false);
        setErrorMsg(err.response.data.message);
        console.log(err.response);
      });
  };
  return (
    <Grid
      container
      spacing={0}
      direction="column"
      alignItems="center"
      justifyContent="center"
    >
      <Head>
        <title>SASO Web App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {isChanged ? (
        <p>
          Your password has been change. Click this{' '}
          <a
            style={{
              color: '#19857b',
              fontWeight: 'bold',
            }}
            href="https://saso.iwkz.de/"
          >
            Link
          </a>{' '}
          to the SASO page
        </p>
      ) : (
        <>
          <DialogTitle>Change Password</DialogTitle>
          <form
            id="login-form"
            onSubmit={handleSubmit}
            onChange={e => handleChange(e.target.name, e.target.value)}
          >
            <DialogContent>
              {/* <DialogContentText></DialogContentText> */}
              <Grid container rowSpacing={3} pt={1}>
                <Grid item xs={12}>
                  <TextField
                    fullWidth
                    name="password"
                    label="New Password"
                    variant="outlined"
                    type="password"
                    required
                  />
                </Grid>
              </Grid>
              <span style={{ color: 'red', fontSize: '12px' }}>{errorMsg}</span>
            </DialogContent>
            <DialogActions>
              {isLoading ? (
                <LoadingButton loading variant="outlined">
                  Submit
                </LoadingButton>
              ) : (
                <Button
                  // onClick={e => {
                  //   console.log('asdasd');
                  //   handleClose();
                  // }}
                  form="login-form"
                  type="submit"
                  disabled={
                    !payload.newPassword || payload.newPassword.length < 1
                  }
                >
                  Change password
                </Button>
              )}
            </DialogActions>
          </form>
        </>
      )}
    </Grid>
  );
}
