import React from 'react';
import Head from 'next/head';
import Menu from '../components/Menu'
import styles from '../styles/Home.module.scss';
import { useSelector } from 'react-redux';

export default function Home() {
  //TODO fetch current event
  const events = useSelector(state => state.event.data);

  return (
    <div className={styles.container}>
      <Head>
        <title>SASO Web App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {events[0] ? (
        <Menu
          event={events[0]}
        />
      ) : (
        <div>
          <h2>No event has been held yet</h2>
        </div>
      )}
    </div>
  );
}
