import Head from 'next/head';
import Image from 'next/image';
import BigLogo from '../components/atoms/BigLogo/BigLogo';
import DynamicContainer from '../components/organisms/DynamicContainer/DynamicContainer';
import Navbar from '../components/organisms/Navbar/Navbar';
import styles from '../styles/Home.module.scss';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <BigLogo />
      <DynamicContainer />
    </div>
  );
}
