import React, { useEffect, useState } from 'react';
import Head from 'next/head';
import BigLogo from '../components/atoms/BigLogo/BigLogo';
import DynamicContainer from '../components/organisms/DynamicContainer/DynamicContainer';
import Navbar from '../components/organisms/Navbar/Navbar';
import Layout from '../components/Layout';
import styles from '../styles/Home.module.scss';
import { useSelector } from 'react-redux';

export default function Home() {
  const [openOrderList, setOpenOrderList] = useState(false);
  const [openOrder, setOpenOrder] = useState(false);

  //TODO fetch current event
  const events = useSelector(state => state.event.data);

  return (
    <div className={styles.container}>
      <Head>
        <title>SASO Web App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {events[0] ? (
        <DynamicContainer
          event={events[0]}
          openOrderList={openOrderList}
          setOpenOrderList={setOpenOrderList}
          openOrder={openOrder}
          setOpenOrder={setOpenOrder}
        />
      ) : (
        ''
      )}
    </div>
  );
}
